name: Validate PR template
on:
  pull_request:
    types:
    - opened
    - edited
    - reopened

jobs:
  check:
    name: Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      pull-requests: read

    steps:
    - name: Check for placeholders
      env:
        PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
      run: |
        if [[ $PULL_REQUEST_BODY =~ 🚨 ]]; then
          echo "::error::Please replace all placeholders containing 🚨"
          exit 1
        fi
    - name: Check for required checkboxes
      env:
        PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
      run: |
        regex="\[ \] \*\*\(Required\)\*\*"
        if [[ $PULL_REQUEST_BODY =~ $regex ]]; then
          echo "::error::Please read and check all required checkboxes"
          exit 1
        fi

